from __future__ import annotations

from dataclasses import asdict, dataclass
from datetime import datetime
import math
from typing import Literal, Sequence

from .competition_profiles import get_profile


Side = Literal["LONG", "SHORT"]
Recommendation = Literal["LONG", "SHORT", "WAIT"]
ManagementAction = Literal[
    "HOLD",
    "PROTECT",
    "PARTIAL_TAKE_PROFIT",
    "EXIT_NOW",
]


AMP_PRICE_VALUE_USD_PER_PRICE_UNIT: dict[str, float] = {
    # CME Group contract multipliers / contract sizes for the verified AMP core universe.
    "CME_MINI:MES1!": 5.0,
    "CME_MINI:MNQ1!": 2.0,
    "CBOT_MINI:MYM1!": 0.5,
    "CME_MINI:M2K1!": 5.0,
    "NYMEX:MCL1!": 100.0,
    "NYMEX:MNG1!": 1_000.0,
    "COMEX_MINI:MGC1!": 10.0,
    "COMEX_MINI:SIL1!": 1_000.0,
    "CME_MINI:M6E1!": 12_500.0,
    "CME_MINI:M6B1!": 6_250.0,
    "CME_MINI:MJY1!": 1_250_000.0,
    "CME_MINI:M6A1!": 10_000.0,
    "CME:MBT1!": 0.1,
    "CME:MET1!": 0.1,
    "CBOT:ZN1!": 1_000.0,
    "CBOT:ZB1!": 1_000.0,
}


RISK_CLUSTER_BY_SYMBOL: dict[str, str] = {
    # Capital.com
    "CAPITALCOM:BTCUSD": "crypto",
    "CAPITALCOM:ETHUSD": "crypto",
    "CAPITALCOM:DOGEUSD": "crypto",
    "CAPITALCOM:EURUSD": "fx_usd",
    "CAPITALCOM:AUDUSD": "fx_usd",
    "CAPITALCOM:USDZAR": "fx_usd",
    "CAPITALCOM:XAUUSD": "metals",
    "CAPITALCOM:XAGUSD": "metals",
    "CAPITALCOM:SPX500": "equity_indices",
    "CAPITALCOM:NAS100": "equity_indices",
    # AMP Futures core feed
    "CME_MINI:MES1!": "equity_indices",
    "CME_MINI:MNQ1!": "equity_indices",
    "CBOT_MINI:MYM1!": "equity_indices",
    "CME_MINI:M2K1!": "equity_indices",
    "NYMEX:MCL1!": "energy",
    "NYMEX:MNG1!": "energy",
    "COMEX_MINI:MGC1!": "metals",
    "COMEX_MINI:SIL1!": "metals",
    "CME_MINI:M6E1!": "fx_usd",
    "CME_MINI:M6B1!": "fx_usd",
    "CME_MINI:MJY1!": "fx_usd",
    "CME_MINI:M6A1!": "fx_usd",
    "CME:MBT1!": "crypto",
    "CME:MET1!": "crypto",
    "CBOT:ZN1!": "rates",
    "CBOT:ZB1!": "rates",
}


def risk_cluster(symbol: str) -> str:
    return RISK_CLUSTER_BY_SYMBOL.get(symbol, "other")


@dataclass(frozen=True)
class PositionState:
    position_id: str
    competition_id: str
    symbol: str
    side: Side
    quantity: float
    entry_price: float
    initial_stop: float
    current_stop: float
    target1: float
    target2: float
    opened_at_utc: datetime
    source_plan_id: str | None = None

    @property
    def initial_risk_price(self) -> float:
        return abs(self.entry_price - self.initial_stop)


@dataclass(frozen=True)
class MarketState:
    current_price: float
    recommendation: Recommendation
    composite_score: float
    recent_recommendations: tuple[Recommendation, ...] = ()
    recent_scores: tuple[float, ...] = ()


@dataclass(frozen=True)
class PositionSizingResult:
    competition_id: str
    symbol: str
    equity: float
    risk_fraction: float
    risk_budget_usd: float
    entry_price: float
    stop_price: float
    price_value_usd_per_price_unit: float
    stop_risk_usd_per_unit: float
    estimated_round_trip_commission_usd_per_unit: float
    proposed_quantity: float
    max_position: float
    projected_open_quantity: float
    risk_amount_usd: float
    risk_cluster: str
    portfolio_risk_cap_usd: float
    cluster_risk_cap_usd: float
    portfolio_risk_before_usd: float
    cluster_risk_before_usd: float
    portfolio_risk_after_usd: float
    cluster_risk_after_usd: float
    risk_budget_limited_by: tuple[str, ...]
    allowed_by_position_limit: bool
    allowed_by_risk_policy: bool
    quantity_is_integer_contracts: bool
    note: str

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass(frozen=True)
class ManagementAdvice:
    position_id: str
    competition_id: str
    symbol: str
    action: ManagementAction
    urgency: Literal["normal", "high", "critical"]
    r_multiple: float
    unrealized_pnl_usd: float | None
    thesis_degraded: bool
    suggested_stop: float | None
    suggested_partial_fraction: float | None
    reasons: tuple[str, ...]

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass(frozen=True)
class RotationCandidate:
    competition_id: str
    from_position_id: str
    from_symbol: str
    to_symbol: str
    to_direction: Side
    score_advantage: float
    reason: str

    def to_dict(self) -> dict:
        return asdict(self)


def _finite_positive(value: float, field: str) -> float:
    number = float(value)
    if not math.isfinite(number) or number <= 0:
        raise ValueError(f"{field}_must_be_positive_finite")
    return number


def price_value_usd_per_price_unit(
    competition_id: str,
    symbol: str,
    *,
    reference_price: float,
) -> float:
    """Return USD P/L generated by a 1.0 price move for one quantity unit.

    Capital.com competition symbols are quoted in USD except USDZAR. For the
    quote-USD instruments, one quantity unit earns/loses roughly one USD for a
    one-unit price move. USDZAR P/L is quoted in ZAR, so the conversion uses the
    current USDZAR reference price.

    AMP Futures values use the official CME/CBOT/NYMEX/COMEX contract
    multipliers for the verified core universe.
    """
    price = _finite_positive(reference_price, "reference_price")
    if competition_id == "amp-futures-sep-2026":
        try:
            return AMP_PRICE_VALUE_USD_PER_PRICE_UNIT[symbol]
        except KeyError as exc:
            raise ValueError("amp_contract_value_unverified") from exc

    if competition_id == "capital-africa-sep-2026":
        if symbol == "CAPITALCOM:USDZAR":
            return 1.0 / price
        profile = get_profile(competition_id)
        if symbol not in profile.max_open_position:
            raise ValueError("capital_symbol_not_allowed")
        return 1.0

    raise ValueError("unknown_competition")


def propose_position_size(
    *,
    competition_id: str,
    symbol: str,
    equity: float,
    risk_fraction: float,
    entry_price: float,
    stop_price: float,
    current_open_quantity: float = 0.0,
    portfolio_open_risk_usd: float = 0.0,
    cluster_open_risk_usd: float = 0.0,
    portfolio_risk_multiple: float = 6.0,
    cluster_risk_multiple: float = 3.0,
) -> PositionSizingResult:
    equity = _finite_positive(equity, "equity")
    entry_price = _finite_positive(entry_price, "entry_price")
    stop_price = _finite_positive(stop_price, "stop_price")
    if not math.isfinite(risk_fraction) or not 0 < risk_fraction <= 0.02:
        raise ValueError("risk_fraction_must_be_between_0_and_0.02")
    if not math.isfinite(current_open_quantity) or current_open_quantity < 0:
        raise ValueError("current_open_quantity_invalid")
    for value, field in (
        (portfolio_open_risk_usd, "portfolio_open_risk_usd"),
        (cluster_open_risk_usd, "cluster_open_risk_usd"),
    ):
        if not math.isfinite(value) or value < 0:
            raise ValueError(f"{field}_invalid")
    if not math.isfinite(portfolio_risk_multiple) or portfolio_risk_multiple < 1:
        raise ValueError("portfolio_risk_multiple_invalid")
    if not math.isfinite(cluster_risk_multiple) or cluster_risk_multiple < 1:
        raise ValueError("cluster_risk_multiple_invalid")

    profile = get_profile(competition_id)
    max_position = profile.max_open_position.get(symbol)
    if max_position is None:
        raise ValueError("symbol_not_allowed")

    value_per_price_unit = price_value_usd_per_price_unit(
        competition_id,
        symbol,
        reference_price=entry_price,
    )
    stop_risk_per_unit = abs(entry_price - stop_price) * value_per_price_unit
    if stop_risk_per_unit <= 0:
        raise ValueError("stop_distance_must_be_positive")

    # Commission is treated as round-trip cost. It is deliberately included in
    # the risk budget instead of assuming frictionless fills.
    commission_per_unit = 2.0 * entry_price * value_per_price_unit * profile.commission_rate
    total_risk_per_unit = stop_risk_per_unit + commission_per_unit
    configured_trade_budget = equity * risk_fraction
    portfolio_cap = equity * risk_fraction * portfolio_risk_multiple
    cluster_cap = equity * risk_fraction * cluster_risk_multiple
    remaining_portfolio = max(0.0, portfolio_cap - portfolio_open_risk_usd)
    remaining_cluster = max(0.0, cluster_cap - cluster_open_risk_usd)
    risk_budget = min(configured_trade_budget, remaining_portfolio, remaining_cluster)
    limited_by: list[str] = []
    if remaining_portfolio + 1e-12 < configured_trade_budget:
        limited_by.append("portfolio_risk_capacity")
    if remaining_cluster + 1e-12 < configured_trade_budget:
        limited_by.append("correlation_cluster_capacity")
    raw_quantity = risk_budget / total_risk_per_unit

    integer_contracts = competition_id == "amp-futures-sep-2026"
    if integer_contracts:
        proposed = float(math.floor(raw_quantity + 1e-12))
    else:
        # Keep precision without pretending to know broker UI quantity steps.
        proposed = math.floor(raw_quantity * 1_000_000.0) / 1_000_000.0

    room = max(0.0, float(max_position) - current_open_quantity)
    proposed = min(proposed, room)
    if integer_contracts:
        proposed = float(math.floor(proposed + 1e-12))

    risk_amount = proposed * total_risk_per_unit
    projected = current_open_quantity + proposed
    portfolio_after = portfolio_open_risk_usd + risk_amount
    cluster_after = cluster_open_risk_usd + risk_amount
    position_limit_allowed = proposed > 0 and projected <= float(max_position) + 1e-12
    risk_policy_allowed = (
        proposed > 0
        and portfolio_after <= portfolio_cap + 1e-9
        and cluster_after <= cluster_cap + 1e-9
    )

    note = (
        "Provisional STC sizing only; human approval and manual order entry required. "
        "Risk fraction and concentration multiples are STC risk controls, not official competition limits."
    )
    if competition_id == "capital-africa-sep-2026":
        note += " Broker quantity-step rounding must be confirmed in the order ticket."

    return PositionSizingResult(
        competition_id=competition_id,
        symbol=symbol,
        equity=equity,
        risk_fraction=float(risk_fraction),
        risk_budget_usd=risk_budget,
        entry_price=entry_price,
        stop_price=stop_price,
        price_value_usd_per_price_unit=value_per_price_unit,
        stop_risk_usd_per_unit=stop_risk_per_unit,
        estimated_round_trip_commission_usd_per_unit=commission_per_unit,
        proposed_quantity=proposed,
        max_position=float(max_position),
        projected_open_quantity=projected,
        risk_amount_usd=risk_amount,
        risk_cluster=risk_cluster(symbol),
        portfolio_risk_cap_usd=portfolio_cap,
        cluster_risk_cap_usd=cluster_cap,
        portfolio_risk_before_usd=portfolio_open_risk_usd,
        cluster_risk_before_usd=cluster_open_risk_usd,
        portfolio_risk_after_usd=portfolio_after,
        cluster_risk_after_usd=cluster_after,
        risk_budget_limited_by=tuple(limited_by),
        allowed_by_position_limit=position_limit_allowed,
        allowed_by_risk_policy=risk_policy_allowed,
        quantity_is_integer_contracts=integer_contracts,
        note=note,
    )


def _direction_sign(side: Side) -> float:
    return 1.0 if side == "LONG" else -1.0


def _opposite(side: Side) -> Side:
    return "SHORT" if side == "LONG" else "LONG"


def _confirmed_opposite(
    side: Side,
    recommendations: Sequence[Recommendation],
    scores: Sequence[float],
    *,
    minimum_confirmations: int = 2,
    minimum_strength: float = 0.55,
) -> bool:
    if len(recommendations) < minimum_confirmations or len(scores) < minimum_confirmations:
        return False
    opposite = _opposite(side)
    recs = recommendations[-minimum_confirmations:]
    vals = scores[-minimum_confirmations:]
    if any(r != opposite for r in recs):
        return False
    if side == "LONG":
        return all(s <= -minimum_strength for s in vals)
    return all(s >= minimum_strength for s in vals)


def supervise_position(position: PositionState, market: MarketState) -> ManagementAdvice:
    """Deterministic, anti-churn position-management decision support.

    It never executes an order. A reversal requires two consecutive strong
    opposite closed-bar signals before it is treated as thesis degradation.
    """
    if market.current_price <= 0 or not math.isfinite(market.current_price):
        raise ValueError("current_price_invalid")
    if not -1.0 <= market.composite_score <= 1.0:
        raise ValueError("composite_score_invalid")

    risk_price = position.initial_risk_price
    if risk_price <= 0:
        raise ValueError("position_initial_risk_invalid")

    sign = _direction_sign(position.side)
    pnl_price = (market.current_price - position.entry_price) * sign
    r_multiple = pnl_price / risk_price

    try:
        value = price_value_usd_per_price_unit(
            position.competition_id,
            position.symbol,
            reference_price=position.entry_price,
        )
        unrealized_pnl = pnl_price * position.quantity * value
    except ValueError:
        unrealized_pnl = None

    stop_hit = (
        market.current_price <= position.current_stop
        if position.side == "LONG"
        else market.current_price >= position.current_stop
    )
    target2_hit = (
        market.current_price >= position.target2
        if position.side == "LONG"
        else market.current_price <= position.target2
    )
    target1_hit = (
        market.current_price >= position.target1
        if position.side == "LONG"
        else market.current_price <= position.target1
    )
    opposite_confirmed = _confirmed_opposite(
        position.side,
        market.recent_recommendations,
        market.recent_scores,
    )

    if stop_hit:
        return ManagementAdvice(
            position_id=position.position_id,
            competition_id=position.competition_id,
            symbol=position.symbol,
            action="EXIT_NOW",
            urgency="critical",
            r_multiple=r_multiple,
            unrealized_pnl_usd=unrealized_pnl,
            thesis_degraded=True,
            suggested_stop=None,
            suggested_partial_fraction=None,
            reasons=("current_price_breached_active_stop",),
        )

    if target2_hit:
        return ManagementAdvice(
            position_id=position.position_id,
            competition_id=position.competition_id,
            symbol=position.symbol,
            action="EXIT_NOW",
            urgency="high",
            r_multiple=r_multiple,
            unrealized_pnl_usd=unrealized_pnl,
            thesis_degraded=False,
            suggested_stop=None,
            suggested_partial_fraction=None,
            reasons=("target2_reached", "protect_realized_competition_score"),
        )

    if opposite_confirmed:
        return ManagementAdvice(
            position_id=position.position_id,
            competition_id=position.competition_id,
            symbol=position.symbol,
            action="EXIT_NOW",
            urgency="high",
            r_multiple=r_multiple,
            unrealized_pnl_usd=unrealized_pnl,
            thesis_degraded=True,
            suggested_stop=None,
            suggested_partial_fraction=None,
            reasons=("two_closed_bars_confirmed_strong_opposite_signal",),
        )

    if target1_hit:
        breakeven = position.entry_price
        protective = (
            max(position.current_stop, breakeven)
            if position.side == "LONG"
            else min(position.current_stop, breakeven)
        )
        return ManagementAdvice(
            position_id=position.position_id,
            competition_id=position.competition_id,
            symbol=position.symbol,
            action="PARTIAL_TAKE_PROFIT",
            urgency="normal",
            r_multiple=r_multiple,
            unrealized_pnl_usd=unrealized_pnl,
            thesis_degraded=False,
            suggested_stop=protective,
            suggested_partial_fraction=0.50,
            reasons=("target1_reached", "reduce_risk_and_protect_remainder"),
        )

    if r_multiple >= 1.0:
        locked_r = 0.25 if r_multiple < 1.5 else 0.50
        if position.side == "LONG":
            suggested = max(position.current_stop, position.entry_price + risk_price * locked_r)
        else:
            suggested = min(position.current_stop, position.entry_price - risk_price * locked_r)
        return ManagementAdvice(
            position_id=position.position_id,
            competition_id=position.competition_id,
            symbol=position.symbol,
            action="PROTECT",
            urgency="normal",
            r_multiple=r_multiple,
            unrealized_pnl_usd=unrealized_pnl,
            thesis_degraded=False,
            suggested_stop=suggested,
            suggested_partial_fraction=None,
            reasons=("position_at_least_one_r_in_profit", "tighten_protection_without_forced_rotation"),
        )

    return ManagementAdvice(
        position_id=position.position_id,
        competition_id=position.competition_id,
        symbol=position.symbol,
        action="HOLD",
        urgency="normal",
        r_multiple=r_multiple,
        unrealized_pnl_usd=unrealized_pnl,
        thesis_degraded=False,
        suggested_stop=position.current_stop,
        suggested_partial_fraction=None,
        reasons=("original_thesis_not_invalidated", "no_confirmed_exit_condition"),
    )


def choose_rotation_candidate(
    *,
    position: PositionState,
    advice: ManagementAdvice,
    current_alignment_score: float,
    opportunities: Sequence[dict],
    minimum_score_advantage: float = 0.25,
) -> RotationCandidate | None:
    """Find a materially better opportunity only after current thesis degrades.

    A stronger signal alone never forces rotation. This prevents score-chasing
    and repeated churn between opportunities.
    """
    if not advice.thesis_degraded:
        return None

    best: tuple[float, dict] | None = None
    for item in opportunities:
        if item.get("competition_id") != position.competition_id:
            continue
        if item.get("symbol") == position.symbol:
            continue
        recommendation = item.get("recommendation")
        if recommendation not in {"LONG", "SHORT"}:
            continue
        if not item.get("locked_trade_plan"):
            continue
        score = abs(float(item.get("composite_score", 0.0)))
        advantage = score - abs(float(current_alignment_score))
        if advantage < minimum_score_advantage:
            continue
        if best is None or advantage > best[0]:
            best = (advantage, item)

    if best is None:
        return None

    advantage, item = best
    return RotationCandidate(
        competition_id=position.competition_id,
        from_position_id=position.position_id,
        from_symbol=position.symbol,
        to_symbol=str(item["symbol"]),
        to_direction=item["recommendation"],
        score_advantage=advantage,
        reason="current_thesis_degraded_and_new_locked_plan_materially_stronger",
    )


def aggregate_open_risk(positions: Sequence[PositionState]) -> dict[str, dict]:
    totals: dict[str, dict] = {}
    for p in positions:
        value = price_value_usd_per_price_unit(
            p.competition_id,
            p.symbol,
            reference_price=p.entry_price,
        )
        risk = p.initial_risk_price * p.quantity * value
        bucket = totals.setdefault(
            p.competition_id,
            {"open_positions": 0.0, "initial_risk_usd": 0.0, "clusters": {}},
        )
        bucket["open_positions"] += 1.0
        bucket["initial_risk_usd"] += risk
        cluster = risk_cluster(p.symbol)
        cluster_bucket = bucket["clusters"].setdefault(
            cluster,
            {"open_positions": 0.0, "initial_risk_usd": 0.0},
        )
        cluster_bucket["open_positions"] += 1.0
        cluster_bucket["initial_risk_usd"] += risk
    return totals



def return_correlation(
    closes_a: Sequence[float],
    closes_b: Sequence[float],
    *,
    minimum_returns: int = 20,
) -> float | None:
    """Pearson correlation of synchronized close-to-close returns.

    This helper assumes the caller has already aligned both close series by
    timestamp. It returns None until enough paired returns exist.
    """
    n = min(len(closes_a), len(closes_b))
    if n < minimum_returns + 1:
        return None

    a = [float(x) for x in closes_a[-n:]]
    b = [float(x) for x in closes_b[-n:]]
    if any((not math.isfinite(x) or x <= 0) for x in a + b):
        return None

    ra = [(a[i] / a[i - 1]) - 1.0 for i in range(1, n)]
    rb = [(b[i] / b[i - 1]) - 1.0 for i in range(1, n)]
    if len(ra) < minimum_returns:
        return None

    ma = sum(ra) / len(ra)
    mb = sum(rb) / len(rb)
    da = [x - ma for x in ra]
    db = [x - mb for x in rb]
    va = sum(x * x for x in da)
    vb = sum(x * x for x in db)
    if va <= 0 or vb <= 0:
        return None
    cov = sum(x * y for x, y in zip(da, db))
    corr = cov / math.sqrt(va * vb)
    return max(-1.0, min(1.0, corr))


def effective_pnl_correlation(
    return_corr: float,
    side_a: Side,
    side_b: Side,
) -> float:
    """Convert underlying-return correlation into position-P/L correlation."""
    if not math.isfinite(return_corr) or not -1.0 <= return_corr <= 1.0:
        raise ValueError("return_correlation_invalid")
    return return_corr * _direction_sign(side_a) * _direction_sign(side_b)
